name: Node.js Build and Test

on:
  push:
    branches: [backend]
  pull_request:
    branches: [backend]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run backend tests
        run: npm test || echo "No tests yet"
        working-directory: ./backend

